Repository jphacks/A_2206, pull requests merged in 2022-10, with the labels that each got.

#13 サーバーがローカルで立ち上がる
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#31 git rebase & feature login
  .eslintcache
  package-lock.json
  package.json
  src/firebase.js
  src/page/HomePage/HomePage.js
  src/page/LoginPage/LoginPage.js
  src/page/TopPage/TopPage.js
  yarn.lock
Labels: フロント, 非機能要件

#42 タブのデザイン完了！
  public/favicon.ico
  public/index.html
Labels: フロント, 非機能要件

#47 Feature/junya/layout for mypage
  src/page/HomePage/HomePage.js
  src/page/HomePage/MyPage.module.css
  src/page/HomePage/achieve.jpeg
  src/page/HomePage/background.jpeg
  src/page/TopPage/TopPage.js
Labels: フロント, 非機能要件

#58 不要なファイルの削除とファイル名の変更
  src/App.js
  src/page/CoursePage/CoursePage.js
  src/page/GoalInputPage/GoalInputPage.js
  src/page/LoginPage/LoginPage.css
  src/page/LoginPage/LoginPage.js
  src/page/MyPage/MyPage.js
  src/page/MyPage/MyPage.module.css
  src/page/MyPage/achieve.jpeg
  src/page/RegisterPage/RegisterPage.js
  src/page/TopPage/TopPage.js
Labels: フロント, 非機能要件

#60 セキュリティは大事だね。
  .gitignore
  src/firebase.js
Labels: フロント, 機能要件, マネジメント
